<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LIN59017991" ignored="0" name="SauceDemoEcommerceTest" tests="3" failures="1" timestamp="20 Jun 2022 06:39:34 GMT" time="14.854" errors="0">
  <testcase name="validateCheckoutPageURLTest" time="0.836" classname="com.SauceDemo.testCases.CheckoutPageTest">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/checkout-step-one.ht] but found [https://www.saucedemo.com/checkout-step-one.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/checkout-step-one.ht] but found [https://www.saucedemo.com/checkout-step-one.html]
	at com.SauceDemo.testCases.CheckoutPageTest.validateCheckoutPageURLTest(CheckoutPageTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateCheckoutPageURLTest -->
  <testcase name="addCheckoutDetailsTest" time="1.775" classname="com.SauceDemo.testCases.CheckoutPageTest"/>
  <testcase name="validateCheckoutDetailsTest" time="2.077" classname="com.SauceDemo.testCases.CheckoutPageTest"/>
</testsuite> <!-- SauceDemoEcommerceTest -->
